site_name: "BioKTool - St. Jude"
repo_url: "https://github.com/kevin-benton/bioktool"

site_description: "Really awesome k based tool"
site_author: "St. Jude Cloud"
copyright: "© 2023 St. Jude Children's Research Hospital"

nav:
  - "Home": "index.md"

theme: cosmo
